name: Build and Test
on:
  push:
  pull_request:
    branches : [ develop ]

env:
  DOTNET_VERSION: '7.x'
  
jobs:
  build:
    runs-on: [ windows-latest ]
    
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
     
    - name: List all projects
      run: dotnet sln Homelan.Core.sln list

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore Homelan.Core.sln
    
    - name: Build
      run: dotnet build --configuration Release --no-restore Homelan.Core.sln
      
    - name: Test
      run: dotnet test --no-restore --collect "Code Coverage" --logger "console;verbosity=detailed" Homelan.Core.sln
